CP and build into /tmp/

diff --git a/ada-project/build b/ada-project/build
--- a/ada-project/build
+++ b/ada-project/build
@@ -1,11 +1,16 @@
 #! /bin/bash
 
-echo "===== Compilation de $1 ====="
-echo
-gnatmake -aI/Sources $1 -D /tmp -o /tmp/exe 
+# exit when any command fails
+set -e
+
+echo "===== Compilation de $1 =====" >&2
+echo >&2
+cp $1 /tmp/
+cd /tmp/
+gnatmake -aI/Sources $1 -o /tmp/exe
 
 echo
 echo
 echo "===== Exécution de $1 ====="
 echo
-./exe
+/tmp/exe
